### ISSUE TITLE
what difference is between '=' and ':=' here and a few lines above?

### ISSUE THREAD

**Issue by vlhell** [BaldaGo/balda-go#21]
https://github.com/BaldaGo/balda-go/blob/fc6b28fb3c61c9b86c3ad050cf2146d33d33f7fd/main.go#L52

**Comment by gabolaev** [comment]
Read more about Go syntax rules :)
If you want to initialize new variable (which is not exist), you need to use `foo := `
if you already have a variable and want to override it's value - use `foo =` without `:`

In general,  `foo := 228` it's an alias for:

``` go
var foo int = 228
```
or
``` go
var foo int
foo = 228
```
As you can see, in this case Go automatically determine the type of variable in `:=`

And if you would try to make something like this:
``` go
alan := 14
alan := 88
```
you will get an error. 
( https://play.golang.org/p/q0lc1BvkREc )
